# Site settings
title: Darren Atherton
email: darren.a.atherton@gmail.com
description: >
  A personal site for Android Developer Darren Atherton, focusing on Android
  software development, mobile UI/UX, technical/personal blog and software portfolio.
baseurl: ""
url: ""
fixedNav: 'true' # true or false
theme: grey # green, blue, orange, purple, grey
twitterUsername: darrenatherton
githubUsername: darrenatherton49
linkedInUsername: darrenatherton
dribbbleUsername:
codepenUsername:
disqusid: darrenatherton49.github.io

collections:
   android-apps:
      output: true
      permalink: /work/:path
   android-libraries:
      output: true
      permalink: /work/:path
defaults:
  -
    scope:
      path: ""
      type: "android-apps"
    values:
      layout: "android_app"
  -
    scope:
      path: ""
      type: "android-libraries"
    values:
      layout: "android_library"

# Build settings
permalink: /:year/:month/:day/:title
markdown: kramdown
include: [_pages]
exclude: [_site, CHANGELOG.md, LICENSE, README.md]
sass:
  style: compressed
