# Setup
title:        Darren Atherton
tagline:      "Hello, I’m Darren Atherton, a software engineer interested in Android, Kotlin, Artificial Intelligence and open-source software."
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Darren Atherton
  url:        http://darrenatherton.co.uk/

# Gems
gems:
  - jekyll-paginate

# Build/other
markdown: kramdown
permalink: /:year/:month/:day/:title.html

githublink: "https://github.com/DarrenAtherton49"
twitterlink: "https://twitter.com/DarrenAtherton"
linkedinlink: "https://linkedin.com/in/darrenatherton"
resumelink: "https://github.com/DarrenAtherton49/resume/blob/master/resume.pdf"
disqusid: darrenatherton49.github.io