# Site settings
title:          Darren Atherton
description:    "Personal blog of Darren Atherton"
url:            "http://darrenatherton.co.uk"
baseurl:        ""

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Darren Atherton
  url:          http://darrenatherton.co.uk
  # email:        

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:day-:month-:year/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus: darrenathertondev